### ISSUE TITLE
Missing decimal separators

### ISSUE THREAD

**Issue by letsberoot** [stefan-niedermann/nextcloud-tables#14]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**
I have a number field with one decimal place. However, when entering a number, e.g. 78,3 or 78.3, neither a comma nor a dot are written into the input field. It is therefore somehow not possible to enter decimal numbers correctly in a table.

**Versions**
 - Nextcloud: 26.0.3
 - Nextcloud Tables: 0.5.1
 - Nextcloud Android: 3.25.0
 - Nextcloud Android Tables: 1.1.0

**Smartphone 1:**
- Device: Fairphone
- Android-Version: 12
- App-Store:
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [x] F-Droid
  - [ ] Huawei AppGallery

**Smartphone 2:**
- Device: Shift 5me
- Android-Version: 8
- App-Store:
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [x] F-Droid
  - [ ] Huawei AppGallery

**Comment by stefan-niedermann** [comment]
Thank you for the report!

This issue should be fixed in `1.1.1` - Please reopen in case it occurs with this or a later version.
