### ISSUE TITLE
Unable to open MENU

### ISSUE THREAD

**Issue by otapol** [stefan-niedermann/nextcloud-tables#39]
Unable to open MENU.  The application crashes immediately.
Ota 
[error.txt](https://github.com/stefan-niedermann/nextcloud-tables/files/13883370/error.txt)

**Comment by otapol** [comment]
App downloaded from google play also not working.

[error__II.txt](https://github.com/stefan-niedermann/nextcloud-tables/files/13883630/error__II.txt)

**Comment by g-work** [comment]
I also got this error when I still had tables that had been created before the server app introduced the possibility to assign emojis to tables. When I deleted them or assigned a new emoji, the android app didn't crash anymore.

**Comment by stefan-niedermann** [comment]
This issue has been fixed and will be rolled out with version `1.1.3`.
