### ISSUE TITLE
Data is saved incorrectly

### ISSUE THREAD

**Issue by Markoise** [stefan-niedermann/nextcloud-tables#7]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

In a field with a star rating, one star less than selected in the app is saved.
But it often happens that the entry was not saved and no star is given at all.
If you enter 0 stars in Nextcloud Tables (Web), 1 star is displayed in the Android app.

1. Edit an existing value 
2. Change a star rating
3. Check the change in the web version if it was saved correctly. That shouldn't be the case.

**Versions**

 - Nextcloud: 26.0.0.2
 - Nextcloud Tables: 0.5.2
 - Nextcloud Android: 3.25.0
 - Nextcloud Android Tables: 1.0.7

**Smartphone (please complete the following information):**
- Device: Pixel 7
- Android-Version: 13 
- App-Store:
  - [x] Google Play Store
  - [x] Google Play Store (Beta channel)
  - [ ] F-Droid
  - [ ] Huawei AppGallery

**Stacktrace**

**Comment by stefan-niedermann** [comment]
Thank you for the report. This issue has been fixed on `master`, the patch will be published with `1.0.8`.
